class LoveControllerPage{
  static List<String> nameListLoveMessages = [
    "The More I Meet U The More\nU Appear New.. The More I\nKnow U The More I Want To\nLove U.. Each Day My Love\nFor U Is My First Love..\nBcoz, Each Day I Feel As If I\nHave Just Started Loving U..!",
    "I Get Jealous, I Get\nMad, I Get Worried, I Get\nCurious.. But, Thats Only\nBcoz I Love U So Much,\nAnd I Dont Want To Lose U..!",
    "Millions And Millions Of Years\nWould Still Not Give Me Half\nEnough Time.. To Describe That\nTiny Instant Of All Eternity\nWhen U Put Ur Arms Around Me..\nAnd, I Put My Arms Around U..!",
    "It Is Not Important That\n'm Beautiful To U..\nIt Is Beautiful That I'm\nImportant To U.. U Are The\nMost Beautiful Thing That\nEver Happened To Me..\nLove U My Sweetheart..!",
    "It's Crazy, The Way You See\nSomeone For 2 Minutes And\nYet It Was The Best Of Your\nDay But, It's Crazier When\nYou Find Yourself Thinking\nAbout That Person For\nThe Next 23 Hrs N 58 Minutes.",
    "You Are Always In My Thoughts,Your Words Reach The Deep\nOf My Heart, Your Pictures\nSupport My Fantasy, Your\nVoice Mesmerized Me, I Can\nHardly Explain It.. But\nFeel So Much Love For You.",
    "I'm So Addicted To You, Your\nSmile Your, Laugh, Your\nYelling, Your Talks, Your\nCrying, Your Care Your Love\nIs My Drug, if I Would Have\nGot You, Its Like A Dream\nCome True. Love You.",
    "I Always Lose Control When\nYou Are By My Side, You Have\nBecome The Light Of My Life,\nI Always Enjoy The Time I\nSpend With You, I Think Im\nFalling In Love With You!",
    "My Sweetest Memory..\nUr Message\nMy Biggest Sadness..\nThe Distance\nMy Biggest Hope..\nI Will See U Soon\nMy Strongest Prayer..\nOur Relation Continues Forever.",
    "I Love You ♡..!!",
    "I Forget The Whole World,\nAnd Lost In Your Silky Soft\nArms I Love This Feeling\nOf Being In Love With You\nI Wanna Be With You\nEvery Day, Every Moments!",
    "My Heart Could Feel You\nMy Mind Could Imagine You\nMy Eyes Could See Yo\nMy Breath Could Sense You\nMy Silence Could Mean You\nI Knew I Loved You\nEven Before I Met You!!",
    "Hearts Could Only Love For\nA While.. Feets Could Only\n\nWalk For Some Miles.. Clothes\nWont Forever Be In Style..But, Having U As My Lover\nIs Forever Worth While..!",
    "Someone Somewhere Dreams\nOf Ur Smile.. And, While\n\nThinking Of U Says Life\nIs Worth While.. So\nWhenever U Are Lonely\nRemember Its True.. SomeoneSomewhere Is Thinking Of U!",
    "I Dont Want To Be Ur\nFavourite Or Ur Best\nI Want To Be Ur Only\nOne And\nMake U Forget The Rest!",
    "I Need 3 Things In My Life:\nThe Sun For The Day..\nThe Moon For The Night..\nAnd,U For The Rest Of My Life..!",
    "When You Touched My Hand\nFor The First Time.. It Was\nA Feeling That Can Be Said\nAs Divine.. My Heart Was\nWaiting For This To Happen\nEvee, I Wanted Nothing More\nThan To Hold It Forever..",
    "One Day You'll Ask Me Which\nIs More Important To Me,\nYou Or My Life. I'll Say,\nOf Course, My Life. And You'll\nGo And Walk Away Without Even\nKnowing That You Are My Life.",
    "1 Minute, 1 Hour, 1 Day\n,1 Month, 1 Year..\nNo Matter How Long,\nI'll Treasure The Times\nWe Have Spent Together..!",
    "No One Can Stop Earth\nIn 11 Months.. No One Can\nStop Sun Rising From\nEast.. No One Can Stop\nMy Messeges For U.. No One\nCan Change My Life Except U..!",
    "Can I Say I Love You ♡ Today?\nIf Not..!!\nCan I Ask You Again Tomorrow?\n\nAnd The Day After Tomorrow?\n\nAnd The Day After That?\nCoz I'll Be Loving YouEvery Single Day Of My Life.",
    "When U Love U Get Hurt,\nWhen U Get Hurt U Hate,\nWhen U Hate U Try To\nForget, When U Try To\nForget U Start Missing..\nWhen U Start Missing U\nFall In Love Again..!",
    "U Maybe A Little Little\nSomething, In This Big\nBig World.. But,\nU Are A Big Big Something,\nIn My Little Little World..!",
    "I Promise To Listen When\nU Talk.. And, Hold U Close\nWhen We Walk.. So Give Ur\nHand In Mine Forever.. As We\nStart Our New Life Together..!",
    "No Matter The Distance Between\nUs.. I Am As Close To U Today\nAs I Was Yesterday.. For As\nLong As U Are In My Heart..\nWe Are Never Truely Far Apart.!",
    "There Is No Place I Would\nWant To Be.. Except For\nhere U Are Close To Me.. Bcoz,\nU Make My Heart Smile, Even\nWhen U Stay Just For A While!",
    "Thinking Of U Makes My Life\nComplete.. U Are My Golden\nCloud.. U Are My Smile..\nU Are All The Soulful\nLove Songs Within My Spirit..\nLike An Angel Calling\nMe Perfect For My Soul..!",
    "U Dont Have Any Idea,\nHow Important U Are To Me..\nAnd,\nI Have No Idea,\nHow To Explain It To U..!",
    "2 Stars In The Sky Cant\nDisappear.. 2 Person That\nWere Once In Love Will\nNever Be Forgotten.. Love\nIs A Word That Many Lips\nCan Say.. But,\nFew Hearts Can Feel...!",
    "Thinking Of U\nKeeps Me Awake..\nDreaming Of U\nKeeps Me Asleep..\nBeing With U\nKeeps Me Alive..!",
    "I'm Not Ur Heart But I\nMiss U.. I'm Not Ur Family\nBut I Care For U.. I'm Not\nUr Blood But I'm Ready To\nShare Ur Pain..\nWhy..? Bcoz, I Love U..!",
    "I Love U With My Heart\nAnd My Soul.. I Know U\nDont Believe In Me.. But,\nTrust Me, My Love Is Deep..\nMy Love Is True.. And,\nIt Will Never Fade..!",
    "You Have Turned Me Mad Such\nThat I Have Forgotten The\nWorld In Your Love My Heart\nHas No Idea About Anybody\nElse Fill The Feeling Of LoveIn Your Every Part I Love You ♡.",
    "Time Is Stopped Too,\nHow And Why It Happened..\nMay You Just Come\nLike Some Prayer..\nYou're The Peace Of Soul..\nYou're My Prayer..",
    "Our Relationship, How I Also\nDo Not Like A Moment Away\nEvery Day, I Live For You\nMy All Time Is For You.. Should\nNot Be A Moment Without You\nYour Name Is On Every Breath..",
  ];
  static List<String> nameListOFRomanticMSG = [
    "Of all the friends I've ever met. Your the one I won't forget. And if I die before you do, I'll go to heaven\nand wait for you.",
    "When the night comes, look at the sky. If you see a falling star, don't wonder why, just make a wish. Trust\nme, it will come true, because I did it and I found you.",
    "Words however special... could never even start, to tell you all the love I have for you within my heart. xXx",
    "I feel something in my heart, it's like a little flame, every time I see you, this flame lights up, this flame is \nspecial for you, because I Love You ♡",
    "Love under the stars... they seem very far, but you are so close the star I love the most.",
    "Somewhere, some1 dreams of your smile & finds your presence in life so worthwhile. So when your lonely, \nremember its true that some1, somewhere, is thinking of u.",
    "Theres a warmth in my heart. It haunts me when you're gone. Mend me to your side and never let go.\nThe more I live The more I know, what's simple is true, I Love You ♡.",
    "Falling in love is when she falls asleep in your arms and wakes up in your dreams",
    "My love, words however special ... could never even start, to tell you all the love I have for you within my \nheart",
    "The day that I'll die, when death replaces birth, I'll recognize angels' faces, because I live with one on \nearth.",
    "Loving you could take my life, but when I look into your eyes, I know you're worth that sacrafice",
    "Heaven is the place where I would be, the day you would stop loving me",
    "I miss you ... I need you ... More and more .... each day ... I Love You ♡ ... more than words ... can ever say.",
    "If a big fat man creeps into your bedroom one night and stuffs you into a bag, Then do not worry 'cause I \ntold Santa I wanted you for christmas",
    "The hardest thing in life is watching someone you love , loving someone else.",
    "Love is hard and will always be, but remember somebody loves you and that one is ME",
    "Don't love 1, don't love 2, but love the 1 who loves you.",
    "The words are easy when the language is LOVE",
    "There is somebody in the world. Diferent from the rest. The sweetest person I know. That is why I Love You\n ♡ so.",
    "You showed me how it is to be loved. Now i know what really love is. 1 day we will be together forever.\n I can't wait to hold you in my arms again.",
    "I love three things: the sun, the moon and you, the sun for the day, the moon for the night and you \nforever.",
    "For the world you are somebody, but for somebody, you are the world! Lots of love, Somebody.",
    "The first time we kissed, I closed my eyes, He closed his eyes, and then.... WE MISSED",
    "Sometimes words are hard to find, to form that perfect line to let you know you're always on my mind",
    "Where ever you're going, I'm going your way",
    "Ferrari's are red, Lambo's are blue... but I am as happy in a mini with you.",
    "For there is a certain someone who makes the grey sky blue, I'm glad to say that one is you.",
  ];
  static List<String> nameListOFHeartAndKiss = [
   "That First Kiss Said I Love You ♡,\nThe Next Said I'll Be There,\nThe Third Said I'm Yours Always.\nMy Heart Replied, I Love You ♡ Too,\nAnd Then I'll Never Leave,\nThe Third Kiss Said It All.",
   "A Kiss Upon The Hand Of\nSomeone You Truly Love,\nIs More Beautiful And\nMore Valuable Than\nAny Diamond Or Gem\nCould Ever Be.",
   "My Love For You Grows More\nWith Each Passing Day, The\nThought Of Your Gorgeous\nFace Takes My Breath Away\nThose Brown Eyes Fill My\nSoul With Happiness\n,Those Luscious Lips\nI Love To Kiss.",
   "Dear Customer!\nYour Kiss Balance Is\nGetting Low!! Please Get\nSomebody And Recharge\nYour Balance Now! You Have\n2 Free Kiss And 3 Minutes\nHug Will Be Expried On\n5th January 2013",
   "Benefits Of Kissing,\nChanges The Taste,\nBurns Calories,\nLips Never Go Dry,\nRelieves Stress,\nMakes Face Muscules Strong.\nSo, Keep Kissing.",
   "If I Reached For Your\nHand,will U Hold It ?\nIf I Hold Out My Arms,will\nU Hug Me ?\nIf I Go For Your Lips,\nWill U Kiss Me?",
   "A Kiss Is A Upper Preparation\nFor A Lower Invasion\nThat Will Lead To Further\nPenetration With Fast Acceleration\nThat Will Build The Next Generation.",
   "Boy: What's Your Biggest Dream?\nGirl : To Be Kissed In The Rain. Urs??\nBoy : To Be The One Kissing You.",
   "In A Kiss:- 0.7gm Protein,\n0.45gm Fat,\n0.19gm Chemical,\n0.50gm Variety Of Bacteria Will Die.\nThis Is True.\nSo Catch Your Lover And Start\nKissing And Be Healthy.",
   "Kiss is a credit because\nit is profitable\nwhen returned.\nSo, lend me a kiss.",
  ];
  static List<String> nameListOFSadLove = [
    "Once A Girl Who Recently\nHad A Break Up Was Asked\nHave U Left Ur Boyfriend\nOr He Had Left U???\n\n\n\nShe Smiled N Said:\nLove Left Us",
    "Most Touching Lines Said\nBy A True Lover To His\nLove While Break Up:\n\n\n\nOf All The Lies You Told Me\n, ''I Love You ♡''\nWas My Favourite' ..!",
    "4getn u is hard 2 do,\n4gtn me is up2 u,\n4gt me not, 4gt me neva,\nbut don't 4get, we're gr8 2gether.",
    "i luved u once u luved me not.\ni luved u twice but i 4got.\nu neva luv me u neva will but even so i luv u still.",
    "My eyes R hurting coz I can't C U,\nMy arms R empty coz I can't hold U,\nMy lips R cold coz I can't kiss U but,\nMy heart is breaking coz I'm not with U!",
    "Have I Told You Latley How Much\nI Am In Love With You???\nNo?? Think About It,\nHave A Great Life..",
    "I know u think u broke my heart\nbut I knew your game right from the start\nI saw your game and played it 2\nso look here I play the jokes on u!",
    "A Lost Thing Could I Never Find,\nNor A Broken Thing Mend\nAnd I Fear I Shall Be All Alone\nWhen I Get Towards The End.",
    "I get so emotional when your not around..\nthink the emotion is called happiness.",
    "IF you broke heart any one.\none day your own heart will\nbroke some one.\nThan you know the pain of\nbroke heart.",
    "The most beautiful words\nby a wounded heart\nI Never Stopped Loving You, I Just Stopped Showing It",
    "Staying far never breaks relation,\nStaying near never builds relation,\nIt's a link between hearts,\nWhich never allows us to forget each other.!!",
    "A man may or may not be happy when he-she win's one's mind.\nBut he must be happy when win's one's trust.\nTrust is the zenith of all relation.",
    "When 2 Ppl In Love Gets\nSeperated They Cant B Frends\nAs They Have Hurted Each Other,\ncan't B Enemies As They\nOnce Loved Each Other.\nD Only Thing They Can\nIs Most Familiar Strangers.",
    "I Woke Up This Morning\nJust Befo' The Break Of Day.\nI Was Bitter, Blue And Black, Lawd.\nThere Ain't Nothing Else To Say.",
    "it hearts when heart breaks\nit breaks whn luv leavez\nur life just freezez\nit gives invisible brusises\nur feelings get shaterred.",
    "OncE A Guy wHo recenTLy hAd a brEaKoff with Her giRL friend\nwas aSkEd ....HAv U leFt uR girL frieNd or sHe left u???\nHe smileD And answerED..\nL0vE LefT us!!!",
    "I heard someone whisper ur name, but when i turned around to c who it was,\ni notice i was alone, then i realize it was my heart telling me that.",
    "The reason it hurt so much to separate is\nbecause\nOUR SOULS ARE CONNECTED...",
    "Please break up with me on a rainy day,\nand meet me under a tree.\nSo when it hurts and I can not breath,\nyou'll hear the rain not me.",
    "Words From A Lover 4 His\nLove After His Breakup:\nPlease Do Not Turn Back N\nFace Me Once More..\nI Dnt Have Another\nHeart 2 Lose.! :-( 4 Me",
    "Touching lines 4m separated lovers:\ndidnt run away 4m yu;I just walkd slowly & it seems that u didnt care enough 2stop me",
    "Love hurts when you breakup with someone.\nHurts even more when someone breaks up with you\nBut love hurts the most,\nwhen the person you love\nhas no idea how you feel.",
    "I Will REMEMBER Him\nNOT\nAs The One Who BROKE My Heart\nBUT\nAs The One Who TAUGHT Me\nHOW\nTo LIVE With Broken Heart\nSTILL..\nLOVE YOU SWT HEART.",
    "Break my heart\ndestroy my soul\nand\nleave me crying\ni'd still love you\nand\ni won't expect you to\nlove me in return...",
    "A LOVELY FACT:\nNobody in the world\ncan have a crystal clear HEART\nBecause everyone's HEART\nhas some scratches scribbled by their DEAR ONES.",
    "What to do when it feels\nWhat to do when it does not heals\nEvery sweet moment of life it steals\nBut heart has only love where it deals.",
    "Love marriages are never success\nCuz they never had a pain\nMarriages are made in heaven\nThats true! Cuz i had failed.",
    "Sometimes I wish I had never met you\nbecause then I could go to sleep at night\nnot knowing there was someone like you out there.",
    "Forgettin you\nis hard to do \n\n.\nforgettin me\nis up to you\n\n.\nforget me not\nforget me never\n\n.\nforget this message\nbut not the sender.",
    "A break up is like a broken mirror.\nIt is better to leave it broken than hurt yourself to fix it.",
    "Better never to have met you in my dream than\nTo wake and reach for hands that are not there.",
    "By the timeyou realise\nThe value of people around you.\nIt might be the time\nFor them to leave you.\nSo, never miss a chance\nTo say, i care for you.",
    "Guess i have to learn\nTo move on because its obvious\nI'm not good enough for him.",
    "I can do without you,\nMy love, in all but two ways:\n1. Sleep without you by my side.\n2. Wake without you by my side.",
    "I hide my tears when i say your name\nbut the pain in my heart is stil the same.\nthough i smile and seem carefree\ntheres no1 who misses u more than me!!",
    "I miss u in every beats of my heart,\nIn every blink of my eyes,\nIn every second of time and\nIn every moments of the day.",
    "I thought you wouldn't hurt me\nI thought you were tired of seeing me cry\nWell now, you won?t be able to\nBecause i'm gaining strength back\nAnd i'm finally going to say goodbye.",
    "I'm going to smile and make you think i'm happy,\nI'm going to laugh,\nSo you don't see me cry,\nI'm going to let you go in style,\nAnd even if it kills me - i'm going to smile.",
    "I'd climb the highest mountain.\nI'd swim the ocean blue\nI'd do anything at all my dear,\nJust to get away from you.",
    "If i get scared,\nWld u hold me tight?\nIf i make a mistake,\nWld u make it rite?\nIf i build a fire,\nWld u watch over e flame?\nIf i say i miss u,\nWld u feel e same?",
    "if i stop thinking of you, will you be gone to me forever?\nBut can you stop thinking of him-her??",
    "If this is goodbye,\nDon't come back\nIf this is the end,\nDon't wake me up.",
    "I now finally realize\nThat there are some\nThings in life that\nI just cant change\nIts over. Goodbye",
    "very cute and painful lines 4ever :\n.\nSometimes how hard I try to not cry...\nThe tearsdrop still fall.\nThats gravity!",
  ];
  static List<String> nameListOFValentine = [
    "Hi baby u know when i say 'i miss u' it's always old one for me, but when u say 'i love u...' really darling it's \nalways new for me MY VALENTINE.",
    "Facebook without friendsPhones without signal,\nFacebook without friends,\nYouTube without music.\nThese are all strange,\nbut none of them are as weird\n as ME without U !\nHappy Valentines Day !",
    "You are my everythingToday new sun has arise,\nAnother day to let you\nknow my love for you.\nEven I tell all day long,\nIt won't be enough.\nSo I'll just say,\nYou are my everything.\nHappy Valentine's Day!",
    "You're the air that I breathe,\nYou're the words that I read,\nYou're the light that I see and,\nYour love is all that I need\nBe with me forever...\nHAPPY VALENTINES DAY!",
    "The best thing I've done in my life is to love you\nThe best gift I've received in my life is your love\nAnd the best thing that has ever happened to me is You\nI Love You ♡, Happy Valentine's Day !",
    "Sweeter than the candies\nLovelier than the red roses\nMore huggable than soft toys\nThat's as special as you're\nWish you a Happy Valentine's Day!",
    "Today new sun has arise,\nAnother day to let you\nknow my love for you.\nEven I tell all day long,\nIt won't be enough.\nSo I'll just say,\nYou are my everything.\nHappy Valentine's Day!",
    "I asked God for a flower, he gave me a bouquet\nI asked God for a minute, he gave me a day\nI asked God for true love, he gave me that too\nI asked for an angel and he gave me you.\nHappy Valentine Day!",
    "I wrote your name in the sky,\nbut the wind blew it away.\nI wrote your name in the sand,\nbut the waves washed it away.\nI wrote your name in my heart,\nand forever it will stay.\nHappy Valentine Day!",
    "You are my heart, my soul, my treasure,\nMy today, my tomorrow, my forever,\nMy everything!\nHappy Valentine Day!",
    "Your eyes, your smile.\nYour touch, your kiss.\nYour promise, your words.\nOur everlasting bliss.\nHappy Valentine Day!",
    "No poems no fancy words\nI just want the world to know\nthat I Love You ♡ my Princess with all my heart.\nHappy Valentines Day.",
    "48+2 Members can sit in a Bus.\n5+1 can sit in a Car.\n3+1 can sit in a auto\n1+1 can sit in a Bike.\nOnly 1 can sit in my Heart,\nThats U My dear valentine",
    "DREAMING of you makes my night worth while\nTHINKING of you makes me * smile *\nHAVING you is the best thing ever, and\nLOVING you is what i plan to do...forever.\nHappy Valentine's Day.",
    "I'm enthralled by your beauty, mesmerized by your charisma and spellbound by your love. No wonder I\n am always thinking about you. I wish to celebrate every Valentine with you. Happy Valentine's Day",
    "Fond thoughts are coming your way;\nWe've always had a special connection,\nSo Happy Valentine's Day!",
    "Hi baby u know when i say 'i miss u' it's always old one for me, but when u say 'i love u...' really darling it's \nalways new for me MY VALENTINE.",
    "U r d beat of my heart\nd 1 I really love\nDont let me out of Ur sight\nFor Im yours by heart\n\nHappy Valentines Day",
    "What i need to live\nhas been given to me\nby the earth\n\nWhy i need to live\nhas been given to me\nby you my valentine !!!\n\n\nHappy Valentines Day",
    "So Many Time\nI Thought Id Never\nFind Sum1 To Love Me\nd Way I Needed 2 B\nLoved Then\nU Came In My Life\n&\nShowed Me\nWh8 True Love\nReally Is\n\nHappy Valentines Day",
    "I Love You ♡ more today than I did yesterday,\nBut not as much as I will tomorrow.\nHappy Valentine's Day!",
    "I won't to kiss ur lips\nI won't to play with ur teeth\nI want to taste ur tongue\nHey ! don't get angry fren\nI m toothpaste.........\n\nHappy valentine dear",
    "White-silent\nBlue-cool\nRed-reserved\npink-lovely\nviolet-naughty\nbrown-isolated\norange-hot\nblack-smart\ngrey-talkative\nWhich color u think suits me?\nReply soon\nmy valentine..",
    "Without Love -- days are sad day, moan day, tears day, waste day, thirst day, fright day, shatter day. \nSo be in love everyday...Wish you a Happy Valentine's Day.",
    "I'm enthralled by your beauty, mesmerized by your charisma and spellbound by your love. No wonder I am always thinking about you. \n I wish to celebrate every Valentine with you. Happy Valentine's Day!",
    "Love so much my heart is sure. As time goes on I Love You ♡ more, Your happy smile. \nYour loving face no one will ever take your place. Wish you a Happy Valentine's Day!",
    "My heart for you will never break. My smile for you will never fade. My love for you will never end. I Love \nYou ♡!",
    "U r unique\nU r caring &\nU r the best\nN Im d luckiest to\nHave U in my life!\nHAPPY VALENTINE'S DAY MY SWEET HEART!",
    "What the heart gives away is never gone, but kept in the hearts of others, from dusk to dawn. \nLove you from the core of my heart. Be my Valentine.",
    "Love is not how long u've been together,\nNot how much u've given or receive,\nNot how many times u've helped each other,\nIt's how u value each other !\nHappy Valentine's Day !",
    "Tears can sometimes be more special than smiles...\nFor smiles can be given to any one...\nBut tears are only shed for people we love!\n\n\nHappy Valentine's Day !",
    "Tonight I ask the stars above,\nHow I'll ever win your love,\nWhat do I do,\nWhat do I say,\nTo turn your angel eyes my way?\nso. Happy Valentine's Day !!!",
    "I searched through books & leafed through cards,\nFor words that wud convey, what I had in my heart,\nBut when I sat down to write, all I can write was....I Luv U!\nHappy Valentine's Day!",
    "You're the air that I breathe,\nYou're the words that I read,\nYou're the light that I see and,\nYour love is all that I need\nBe with me forever...\nHAPPY VALENTINES DAY!",
    "Tonight I ask the stars above,\nHow I'll ever win your love,\nWhat do I do,\nWhat do I say,\nTo turn your angel eyes my way?\nBe my Valentine",
    "AA JEEVIDI YEA GAMYAMMO NAA EEEEE NUVVU YEA JANMMA BANDAMO NINNUCHEARUKOVADAM KOSAM NAA EEE ANWEASHANA NAA NEREEKASHANA",
    "Feelings are always the same\nSaying it could be in different ways\n,Some say it directly are called 'LOVERS'\nSome write them on paper & are called 'POETS' =)\n\n() Happy Valentines Day ()",
    "Love Is A Driver ...\nBitter And Fierce\nIf You Fight And\nResist Him,\n\nEasy-going\n,Once You\nAcknowledge His\nPower . . . :)",
    "My Heart To You Is Given,\nOh Dear, Do Give Yours To Me,\n\nWe'll Lock Them Up Together\nAnd Throw Away The Key :)",
    "U dnt hav 2 ask f i care. in evry word u say, fil free 2 tel ur worries & realyz dt im here 4 now 4 always & 4 evr 4u exclusvely...Happy Valetines Day",
    "Every Boy's wish:\nI'm not a Prince but my life-partner should be a Princess.\nTrue Lover's wish:\nMy life-partner may not be a Princess but I promise I'll treat her like a Princess!\nHappy Valentine's day 2025",
    "If I die and go to heaven,\nI put your name on a golden star.\nSo that all the angels can see how much you mean to me.\nI Love You ♡",
    "u r my summer breeze my winter sun\nu r my spring time fun\nu r my special one\nu r my love, only one",
    "You are my sun and stars, my night, my day,\nMy seasons, summer, winter, my sweet spring,\nMy world, my thoughts, my breath, my future\nMy all, my love, my Valentine",
    "My love for you is like water,\nFalling countless\nThe beating of my heart for you\nIs heavy and soundless,\nThe feeling of being in your arm is\nPrecious and endless......",
    "my heart,,\nif u don't believe in my words,,\nso try to pull my heart,,\nu will c ur name on every wall of my heart",
    "ma heart is like an open book,\nit depends on hw u read me.\nDnt judge me by my cover...\nLuk in and discovr...\nI will b ur nly true lover\nforever",
    "cannot live without your love -\nMy life would not be the same;\nFor I would be incomplete,\nLike a candle without a flame.....",
    "ove is like a CD track\nThat links our hearts together\nDont ever break that CD coz\nThat wud break my heart too.....",
    "If you love me, let me know.\nIf you don't, please let me go.\nA very happy Valentines' day!",
    "Love is what I see in, your smile every day.\nLove is what I feel in, every touch you give.\nLove is what I hear in, every word you say.\nLove is what we share, every day we live.",
    "Wen a TOUCH could HEAL a wound\nWen EYESS cud SPEAK volumes\nWen a SMILE can confirm I M THERE\nthen why do v need owrds 2 sayI Love You ♡...........",
    "Love is 2 souls\nintertwined in such a way\nyou cant find their meeting place\nnor can you tear it apart\nit is one embodiment of\npure pleasure & pain ,\njoy & sorrow",
    "Perfact love is not receiving,\nit is giving and forgiving.\nperfact love is not red roses on valentine day,\nits the rest of 364 days of knowing you love someone.",
    "Ull always be mine 4 now & 4ever.\nUll always be mine 4 u r my treasure.\nUll always be mine please tell me its true.\nPlease be mine 4ever. Ill always luv u",
    "Every Hour I think of you\nEvery Minute I think of you\nEvery Second I think of you\nI live for you and I die for you\nIt's not for days; it's not for weeks,\nIt's not for months or years, its forever.",
    "Love so much my heart is sure. \nAs time goes on I Love You ♡ more,\nYour happy smile. Your loving face no one will ever take your place.\nWish you a Happy Valentines Day!",
    "I wanted 2 send U all my love but d postman said\nhe also having a date with his girlfriend.\nSo I m sending u Message by mobile. .......",
    "Every time i miss you, a star falls.\nSo if you ever look up at the sky and the stars are gone, its because you made me miss you too much!\nBe my Valentine!",
    "There are Tulips in my garden, there are Tulips in the park,\nbut nothing is more be beautiful than our two lips meeting in the dark! valentines day wishes",
    "DREAMING of you makes my night worth while\nTHINKING of you makes me * smile *\nHAVING you is the best thing ever, and\nLOVING you is what i plan to doforever.\nHappy Valentines Day.",
    "Tears can sometimes be more special than smiles\nFor smiles can be given to any one\nBut tears are only shed for people we love!\nHappy Valentines Day !.......",
    "Im enthralled by your beauty, mesmerized by your charisma and spellbound by your love. No wonder I am always thinking about you. \nI wish to celebrate every Valentine with you. Happy Valentines Day.",
    "Near ones r not dear, Dear ones r not near. It is easy to remember the near ones. But... Very difficult to \nforget the dear ones. Happy Valentine Day.",
  ];
  static List<String> nameListOFCrush = [
   "3 C's of LIFE: Choice, Chance, Change ' You must \nmake a choice to take a chance or your life will \nnever change.",
   "A friendship that is transformed into a \nrelationship beats a crush any day :)",
   "A good heart and a good nature are two \ndifferent issues, A good heart can win many \nrelationships, But a good nature can win many \ngood hearts.",
   "A great relationship is about two main things.\n First, find out the similarities. Second, respect \nthe differences.",
   "A heart that loves is always young.",
   "A person who irritates you is always the one \nwho loves you very much but fails to express it.",
   "A person who truly loves you, is someone who \nsees the pain in your eyes, while everyone else \nbelieves in the smile on your face.",
   "A scond chance means nothing if nothing\n is learned from past mistakes.",
   "Ability is what you're capable of doing, \nmotivation determines what you do, and \nattitude determines how well you do it.",
   "Accept that you have lost, but never accept that]\n you have failed.",
   "Advice is what we ask for when we already \nknow the answer but wish we didn't.",
   "All I want is to feel your arms around me and \nhear you say something sweet in my ear and \nforget everything else but I know you don't feel the same way...",
   "All the treasure in the world is worthless, unless \nyou have someone to share it with.",
   "Always appreciate the time you get, because \nyou never know how much longer it`ll last.",
   "An open mind leaves a chance for someone to \ndrop a worthwhile thought in it.",
   "Are we not like two volumes of one book?",
   "Are you an alarm clock? You managed to wake up \nmy sleeping heart.",
   "Argument may win the situation but lose the \nperson, but Patience may lose the situation but\n win the person.",
   "Awesome lines by Charlie Chaplin 'You need \nPower, only when you want to do something \nHarmful', Otherwise'.. 'Love is Enough to get everything done'. :-)",
   "Based on studies, the average crush lasts 4\nmonths...If it lasts longer...you've fallen in love...",
   "Be careful with your words once they said, they \ncan only be forgiven but never forgotten.",
   "Be nice to people on your way up because you \nmeet them on your way down.",
   "Be confident. You`ll never get anywhere if you \ndon`t believe in yourself.",
  ];
  static List<String> nameListOFLoveStories = [
    "A girl asked a boy if she was pretty, he said No.\nShe asked him if he wanted to be with her forever,\n he said No.Then she asked him if he \nwould cry if she walked away, he said No. She \nhad heard enough; she needed to leave.\nAs she walked away he grabbed her arm and \ntold her to stay. He said You're not pretty, you're \nbeautiful. I don`t want to be with you forever, I\nneed to be with you\n forever. And I wouldn't cry if you walked away, I would die.",
    "A man bought 12 flowers. 11 real and 1 fake. He said,\n I will love you until the last flower dies.",
    "Boy: Can I take a photo?\nGirl: Why?\nBoy: I just want to show my children how their mom looked when she was younger.",
    "There was a girl named Becca and a boy named Joe. \nBecca was in a burning house. None of the firefighters \ncould get in the house because the fire was too big. Joe \ndressed in one of the fire suits and got into the house. \nWhen he got up the stairs, the steps fell off behind him.\n When he got into her room he sealed the door up behind him.\n He held her tight, kissed her, huged her, then said that \nhe loved her. She asked what was wrong, and he \nsaid that he was going to die. Her eyes widened as she \nbegan to cry. He picked her up and jumped out of the \nfour story house. He landed on his back with her on top \nof him. He died to save her life.",
    "There was girl who loved a boy so much she said to the boy, If I told you that I liked you, would you take it as a joke?\nThe boy said, Yes I would.\nShe asked, Why?\nThe boy replied,Because I know you don't like me, I know you love me!",
    "A girl and guy were speeding over 100 mph on a motorcycle.\nGirl: Slow down. I'm scared.\nGuy: No this is fun.\nGirl: No its not. Please, it's too scary!\nGuy: Then tell me you love me.\nGirl: Fine, I Love You ♡. Slow down! Guy: Now give me a big hug. (Girl hugs him)\nGuy: Can you take my helmet off and put it on? It's bugging me.\nIn the paper the next day: A motorcycle had crashed into a \nbuilding because of brake failure. Two people were on \nthe motorcycle, but only one survived. The truth was \nthat halfway down the road, the guy realized that his\n brakes broke, but he didn't want to let the girl know. \nInstead, he had her say she loved him, felt her hug one \nlast time, then had her wear his helmet so she would live\n even though it meant he would die.",
    "Me and my boyfriend were out to dinner and there was an older couple sitting near us.\n\nAll of a sudden I heard the older man say \nRemember when we were like that? I looked at \nmy boyfriend and we laughed and giggled.\n\nWhen I turned back around, my boyfriend had a \nring in his hand, and said I can't wait until we're \nlike that!",
    "Once a guy said to a girl: Love is like a rainbow, it's colourful and makes people smile.\nLove is like an ocean, it's deep and beautiful.\nLove is like the sun, it shines and it's warm.\nLove is like rain, it's calm and refreshing.\nWill you let me show you that love?\n\nThe girl shook her head while smiling: No\n\nThe guy looked down sadly and then he heard her saying these words: I want you to show me YOUR love...",
    "One day, a lover was angry with his girlfriend \nand tried to stab her with a knife. He accidentally \ncut his own finger badly with the\n knife, started bleeding, and knelt down in pain.\n His girlfriend bent down and bandaged up his \nfinger and tended to him.",
    "There was a blind girl who was filled with animosity and despised the world. She didn't have many friends, just a boyfriend who loved her deeply, like no one else. She always used to say that she'd marry him if she could see him. Suddenly, one day someone donated her a pair of eyes.\n\nAnd that's when she finally saw her boyfriend. She was astonished to see that her boyfriend was blind. He told her, You can see me now, can we get married?\n\nShe replied, And do what? We'd never be happy. I have my eye sight now, but you're still blind. It won't work out, I'm sorry.\n\nWith a tear in his eye and a smile on his face, he meekly said, I understand. I just want you to always be happy. Take care of yourself, and my eyes.",
    "Boy: I would like you to do something important \nfor me.\nGirl: Yes?\nBoy: When you get home today, thank your mom for me.\nGirl: Sure, but why?\nBoy: Thank her because she gave birth to an angel who was put into my life and one day whom I hope will become my wife.",
    "When my boyfriend and I were 15, he wanted to give me a piggy back ride, but I refused because I thought I was too fat.\n\nHe picked me up and said, You better get used to this, because I'm picking you up like this on our wedding day.\n\nWe got married last week and he carried me just like he said he would.",
    "One night a guy and a girl were driving home from the movies. The boy sensed there was something wrong because of the painful silence they shared between them that night. The girl then asked the boy to pull over because she wanted to talk. She told him that her feelings had changed and that it was time to move on.\nA silent tear slid down his cheek as he slowly reached into his pocket & passed her a folded note.\nAt that moment, a drunk driver was speeding down that very same street. He swerved right into the drivers seat, killing the boy. Miraculously, the girl survived. Remembering the note, she pulled it out & read it. Without your love, I would die.",
    "Today, my boyfriend told me that he loved me. When I asked why, he took out a list. It was 301 reasons long, and he said he had a pen in his pocket in case he remembered any new reasons.",
    "A boy was dating a girl who always hurt him. One day, she broke up with him and told him, I don't ever want to see you again.\n\nA few months later, the girl had a change of heart. She realized that she loved the boy, so she went back and said to him, Give me just one more chance. I Love You ♡ and I need you. I promise that I will never hurt you again.\n\nBut the boy just laughed and said to her, Only a fool would take back someone who hurt them so much.\n\nThe girl felt hopeless and began to cry, but the boy put his arms around her, held her tightly and said, ...and I am one of those fools.",
    "When my sister was younger she came home from school one day and demanded that I take her to the library so she could get books on sign language\n\nI asked why? She told me there was a new kid at school who was deaf and she wanted to befriend him.\n\nToday I stood beside her at their wedding watching her sign I do.",
  ];
  static List<String> nameListOFAnniversaryWishes = [
   "1st anniversary\nWishing you all the best on your 1st anniversary and many more to come. I know a determined person like you will continue to succeed in all things you do.",
   "5th anniversary\nCongratulations on your 5th anniversary. This is a time for celebrating, happiness, and plenty of joy so smile and know that you are thought of during this special time.",
   "10th anniversary\nI am so happy for you and yours as you celebrate your 10th anniversary. I wish you many more years of happiness and success.",
   "15th anniversary\nSending you lots of love and happy thoughts during this amazing milestone in your life. A 15th anniversary deserves recognition as it only happens once in a lifetime.",
   "20th anniversary\nIt is your 20th anniversary! Remember this as a time in your life when you can look back and smile knowing that you succeeded in all things.",
   "25th anniversary\nThis is a truly amazing time in your life and I wanted to send my thoughts and well wishes to you. Wishing you a wonderful 25th anniversary.",
   "30th anniversary\nI wanted to send you big, heartfelt congratulations on your very special 30th anniversary. This is a once in a lifetime experience.",
   "50th anniversary\nWelcome to the golden years of your life brought on by a 50th anniversary. Please accept my congratulations to you.",
   "55th anniversary\nI heard that you were celebrating a 55th anniversary. Sending you thoughtful wishes and plenty of love and happiness during this special time.",
   "100th anniversary\nA 100th anniversary is a very special moment in life. I am glad to be a part of this time so I can express my heartfelt joy to you.",
  ];
  static List<String> nameListOFMarriageWishes = [
    "A happy marriage is one that is built on love, \ntrust, and mutual respect.",
    "Don't look at your marriage as your life ending; \nbut rather, the life with your special loved one \njust beginning.",
    "Here's hoping that your marriage is a successful \none.",
    "Don't bother with the something white and something blue; the only thing you need on your wedding day is each other.",
    "Getting married is a joyous occasion, full of nervousness and uncertainty. Your wedding is one day that will truly bring you joy and memories that will last a lifetime.",
    "Choosing to spend your life together is no easy task; but when the decision to get married is made, you shouldn't have to ask.",
    "Cherish the one you love and the one you're with; being married to one and the same is a very special gift.",
    "The wedding bells that ring today are in celebration of your love for each other. Wishing you a happy wedding and a wonderful life together in the future.",
    "Getting married is all about what happens next.",
    "Don't be uncertain about your wedding; the uncertainty can be exciting at the same time.",
    "Your wedding day is a celebration of love, so be happy for all the moments you'll share together.",
    "Capture all the joy you'll experience on your wedding and save it for the long future ahead.",
    "Weddings can be too much about how to decorate the room, when they should be all about the happiness of the bride and groom.",
    "Years from now, you'll remember your wedding day as if it were yesterday.",
    "You might forget certain memories here and there, but you'll never forget your wedding day.",
    "You'll experience all types of emotions at your wedding, but you'll be able to go through them together, and that's what's important.",
    "Have a happy wedding and a blissful honeymoon!",
    "May all of your dreams come true on your wedding day, and may those dreams become reality afterwards.",
    "The marriage bond is one that lasts through all sorts of trials and tribulations. ",
    "Here's to you forging your own today.",
    "Here's to having a joyful wedding, and may you continue to love and support each other through all the highs and lows in the future.",
    "Being married is truly a labor of love. Have a happy wedding!",
  ];
  static List<String> nameListOFRomanticQuotes = [
    "Love me and the world is mine.\n - David Reed",
    "Looking back, I have this to regret, that too often when I loved, I did not say so.\n - David Grayson",
    "I Love You ♡, not only for what you are, but for what I am when I am with you.\n - Roy Croft",
    "If you love something, set it free; if it comes back it's yours, if it doesn't, it never was.\n - Richard Bach",
    "A relationship is like a rose,\nHow long it lasts, no one knows;\nLove can erase an awful past,\nLove can be yours, you'll see at last;\nTo feel that love, it makes you sigh;\nTo have it leave, you'd rather die;\nYou hope you've found that special rose,\nCause you love and care for the one you chose.\n - Rob Cella",
    "It is better to break one's heart than to do nothing with it.\n - Margaret Kennedy",
    "You will find as you look back upon your life, that the moments when you have really lived, are the moments when you have done things in the spirit of love.\n - Henry Drummond",
    "What the world really needs is more love and less paper work.\n - Pearl Bailey",
    "Love is a game that two can play and both win.\n - Eva Gabor",
    "Love is, above all, the gift of oneself.\n - Jean Anouilh",
    "Tis better to have loved and lost Than never to have loved at all.\n - Alfred, Lord Tennyson",
    "You never lose by loving. You always lose by holding back.\n - Barbara DeAngelis ",
    "You come to love not by finding the perfect person, but by seeing an imperfect person perfectly.\n - Sam Keen ",
    "It's easy to fall in love. The hard part is finding someone to catch you. - Bertrand Russell",
    "Love is like a friendship caught on fire. In the beginning a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.\n - Bruce Lee ",
    "Love doesn't make the world go round. Love is what makes the ride worthwhile.\n - Franklin P. Jones",
    "If you judge people, you have no time to love them.\n - Mother Teresa",
    "Immature love says, I Love You ♡ because I need you. Mature love says, I need you because I Love You ♡.\n- Erich Fromm",
    "The quality of love and the duration of a relationship are in direct proportion to the depth of the commitment by both people to making the relationship successful. Commit yourself wholeheartedly and unconditionally to the most important people in your life.\n - Brian Tracy",
    "For you see, each day I Love You ♡ more. Today more than yesterday and less than tomorrow.\n - Rosemonde Gerard",
    "Never close your lips to those whom you have opened your heart.\n - Charles Dickens",
    "Of all forms of caution, caution in love is perhaps the most fatal to true happiness.\n - Bertrand Russell",
    "Love is the condition in which the happiness of another person is essential to your own. - Robert Heinlein",
    "When the power of love, overcomes the love of power, the world will know peace. - Jimi Hendrix",
    "How on earth are you ever going to explain in terms of chemistry and physics so important a biological phenomenon as first love?\n - Albert Einstein",
    "Two things only a man cannot hide: that he is drunk and that he is in love.\n - Antiphanes",
  ];
  static List<String> nameListOFBabyWishes = [
    "Sending happy thoughts your way as you prepare to welcome a little someone new to your family.",
    "Wishing you and your family the best on the coming birth of a new special person.",
    "Cherish every moment of everyday between you, your family, and your new little bundle of joy.",
    "Congratulations on the upcoming birth of your new baby. Wishing you the best in health and happiness.",
    "Children are considered a gift. May your home be blessed with the gift of your new baby.",
    "We are all looking forward to the arrival of the newest addition to your family.",
    "The addition of a new baby brings with it the chance to love and cherish to your heart’s content.",
    "Congratulations on the new life you are getting ready to bring into the world.",
    "You are going to be a wonderful mother to your new little bundle of joy.",
    "I am so happy to know your family will soon have an additional member.",
    "Best wishes and plenty of health throughout the remainder of your pregnancy. We look forward to meeting your new baby.",
  ];
}